In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [2]:
from keras.applications import imagenet_utils
from keras.preprocessing.image import img_to_array
from keras.preprocessing.image import load_img
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split
from keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.optimizers import RMSprop
from tensorflow.keras.applications import VGG16
from keras.layers import Input
from keras.models import Model
from keras.layers.core import Dense
from keras.layers.core import Dropout
from keras.layers.core import Flatten
import numpy as np
import random
import os
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from imutils import paths
from tensorflow.keras.applications import VGG16

In [ ]:
image_path = list(paths.list_images('/content/gdrive/MyDrive/code_nhandien_chuso/data_new/'))

for i in image_path:
  print(i)
print(len(image_path))

In [4]:
random.shuffle(image_path)

In [5]:
labels = []
labels1 = []
for p in image_path:
  labels.append(p.split(os.path.sep)[-2])
  labels1.append(p.split(os.path.sep)[-2])
print(labels)
print(len(labels))

['-1', '7', '5', '2', '5', '4', '2', '5', '3', '1', '2', '3', '7', '8', '1', '4', '5', '3', '1', '7', '1', '0', '9', '8', '4', '6', '8', '2', '7', '9', '0', '1', '0', '0', '4', '0', '2', '0', '0', '8', '7', '2', '0', '6', '0', '3', '6', '9', '2', '9', '1', '8', '4', '1', '1', '1', '8', '0', '8', '4', '4', '9', '2', '0', '0', '0', '1', '6', '6', '5', '6', '6', '0', '0', '1', '-1', '-1', '4', '3', '2', '6', '8', '5', '5', '-1', '9', '5', '8', '0', '0', '2', '8', '-1', '1', '2', '0', '0', '5', '2', '9', '0', '-1', '5', '5', '8', '2', '8', '6', '1', '0', '-1', '2', '3', '-1', '0', '8', '1', '8', '-1', '2', '6', '8', '5', '4', '6', '6', '0', '8', '1', '-1', '6', '0', '2', '5', '2', '9', '0', '2', '7', '5', '2', '5', '4', '-1', '1', '9', '0', '4', '7', '-1', '2', '0', '6', '-1', '8', '5', '2', '3', '4', '6', '4', '9', '0', '-1', '0', '7', '0', '5', '0', '2', '-1', '0', '6', '5', '1', '2', '0', '0', '0', '0', '4', '0', '0', '0', '1', '6', '0', '2', '1', '-1', '5', '0', '1', '5', '9', '-1', '5

In [6]:
le = LabelEncoder()
print(labels1)
labels = le.fit_transform(labels)
print(labels)

print(len(labels1), len(labels))

['-1', '7', '5', '2', '5', '4', '2', '5', '3', '1', '2', '3', '7', '8', '1', '4', '5', '3', '1', '7', '1', '0', '9', '8', '4', '6', '8', '2', '7', '9', '0', '1', '0', '0', '4', '0', '2', '0', '0', '8', '7', '2', '0', '6', '0', '3', '6', '9', '2', '9', '1', '8', '4', '1', '1', '1', '8', '0', '8', '4', '4', '9', '2', '0', '0', '0', '1', '6', '6', '5', '6', '6', '0', '0', '1', '-1', '-1', '4', '3', '2', '6', '8', '5', '5', '-1', '9', '5', '8', '0', '0', '2', '8', '-1', '1', '2', '0', '0', '5', '2', '9', '0', '-1', '5', '5', '8', '2', '8', '6', '1', '0', '-1', '2', '3', '-1', '0', '8', '1', '8', '-1', '2', '6', '8', '5', '4', '6', '6', '0', '8', '1', '-1', '6', '0', '2', '5', '2', '9', '0', '2', '7', '5', '2', '5', '4', '-1', '1', '9', '0', '4', '7', '-1', '2', '0', '6', '-1', '8', '5', '2', '3', '4', '6', '4', '9', '0', '-1', '0', '7', '0', '5', '0', '2', '-1', '0', '6', '5', '1', '2', '0', '0', '0', '0', '4', '0', '0', '0', '1', '6', '0', '2', '1', '-1', '5', '0', '1', '5', '9', '-1', '5

In [7]:
dict_tmp = {}
for i in range(len(labels1)):
    dict_tmp[labels[i]] = labels1[i]

print(dict_tmp)
print(len(dict_tmp))

{0: '-1', 8: '7', 6: '5', 3: '2', 5: '4', 4: '3', 2: '1', 9: '8', 1: '0', 10: '9', 7: '6'}
11


In [8]:
# One-hot encoding
lb = LabelBinarizer()
labels = lb.fit_transform(labels)
print(labels)
print(labels.shape)

[[1 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(807, 11)


In [9]:
import cv2

In [10]:
list_image = []
for (j, imagePath) in enumerate(image_path):
  image = load_img(imagePath, target_size=(28, 28), grayscale= True)
  print(image.size)
  image = img_to_array(image)
  
  print('hihi',image.shape)
  image = np.expand_dims(image, 0)
  # image = imagenet_utils.preprocess_input(image)
  print(image.shape)
  # print(image)
  list_image.append(image)
list_image = np.vstack(list_image)
print(list_image.shape)

/usr/local/lib/python3.7/dist-packages/keras_preprocessing/image/utils.py:107: UserWarning: grayscale is deprecated. Please use color_mode = "grayscale"
  warnings.warn('grayscale is deprecated. Please use '


(28, 28)
hihi (28, 28, 1)
(1, 28, 28, 1)
(28, 28)
hihi (28, 28, 1)
(1, 28, 28, 1)
(28, 28)
hihi (28, 28, 1)
(1, 28, 28, 1)
(28, 28)
hihi (28, 28, 1)
(1, 28, 28, 1)
(28, 28)
hihi (28, 28, 1)
(1, 28, 28, 1)
(28, 28)
hihi (28, 28, 1)
(1, 28, 28, 1)
(28, 28)
hihi (28, 28, 1)
(1, 28, 28, 1)
(28, 28)
hihi (28, 28, 1)
(1, 28, 28, 1)
(28, 28)
hihi (28, 28, 1)
(1, 28, 28, 1)
(28, 28)
hihi (28, 28, 1)
(1, 28, 28, 1)
(28, 28)
hihi (28, 28, 1)
(1, 28, 28, 1)
(28, 28)
hihi (28, 28, 1)
(1, 28, 28, 1)
(28, 28)
hihi (28, 28, 1)
(1, 28, 28, 1)
(28, 28)
hihi (28, 28, 1)
(1, 28, 28, 1)
(28, 28)
hihi (28, 28, 1)
(1, 28, 28, 1)
(28, 28)
hihi (28, 28, 1)
(1, 28, 28, 1)
(28, 28)
hihi (28, 28, 1)
(1, 28, 28, 1)
(28, 28)
hihi (28, 28, 1)
(1, 28, 28, 1)
(28, 28)
hihi (28, 28, 1)
(1, 28, 28, 1)
(28, 28)
hihi (28, 28, 1)
(1, 28, 28, 1)
(28, 28)
hihi (28, 28, 1)
(1, 28, 28, 1)
(28, 28)
hihi (28, 28, 1)
(1, 28, 28, 1)
(28, 28)
hihi (28, 28, 1)
(1, 28, 28, 1)
(28, 28)
hihi (28, 28, 1)
(1, 28, 28, 1)
(28, 28)
hihi (2

In [11]:
from tensorflow.keras.layers import Dense, Conv2D, MaxPooling2D, Dropout, Flatten
from tensorflow.keras.models import Sequential

model = Sequential()
model.add(Conv2D(32, (3, 3), padding='same', activation='relu', input_shape=(28, 28, 1)))
model.add(Conv2D(32, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Conv2D(64, (3, 3), padding='same', activation='relu'))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Conv2D(64, (3, 3), padding='same', activation='relu'))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(11, activation='softmax'))

In [12]:
X_train, X_test, y_train, y_test = train_test_split(list_image, labels,test_size=0.15, random_state=42)
X_train = X_train
X_test = X_test
print(X_train.shape)
print(len(y_train))
print(X_test.shape)
print(len(y_test))

(685, 28, 28, 1)
685
(122, 28, 28, 1)
122


In [13]:
aug_train = ImageDataGenerator(rotation_range=30, \
width_shift_range=0.1, height_shift_range=0.1, \
shear_range=0.2, zoom_range=0.2, horizontal_flip=False, \
fill_mode='nearest')

trn_aug = ImageDataGenerator(featurewise_center = True, featurewise_std_normalization = True,
                             rotation_range=30, width_shift_range=0.1,height_shift_range=0.1,
                             shear_range=0.2, zoom_range=0.2, horizontal_flip=False,fill_mode="nearest")
val_aug = ImageDataGenerator(featurewise_center = True, featurewise_std_normalization = True)

In [15]:
aug_test= ImageDataGenerator()

In [17]:
opt = RMSprop(0.001)
numOfEpoch = 800
opt = SGD(0.01)
model.compile(opt, 'categorical_crossentropy', ['accuracy'])
H = model.fit_generator(trn_aug.flow(X_train, y_train, batch_size=32),
                        steps_per_epoch=len(X_train)//32,
                        validation_data=(val_aug.flow(X_test, y_test, batch_size=32)),
                        validation_steps=len(X_test)//32
                        ,epochs=numOfEpoch)

Epoch 1/800


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/keras_preprocessing/image/image_data_generator.py:720: UserWarning: This ImageDataGenerator specifies `featurewise_center`, but it hasn't been fit on any training data. Fit it first by calling `.fit(numpy_data)`.
  warnings.warn('This ImageDataGenerator specifies '
/usr/local/lib/python3.7/dist-packages/keras_preprocessing/image/image_data_generator.py:728: UserWarning: This ImageDataGenerator specifies `featurewise_std_normalization`, but it hasn't been fit on any training data. Fit it first by calling `.fit(numpy_data)`.
  warnings.warn('This ImageDataGenerator specifies '


21/21 [==============================] - 1s 34ms/step - loss: 0.1146 - accuracy: 0.9587 - val_loss: 0.4676 - val_accuracy: 0.8958
Epoch 2/800
21/21 [==============================] - 1s 32ms/step - loss: 0.1258 - accuracy: 0.9525 - val_loss: 0.3376 - val_accuracy: 0.9479
Epoch 3/800
21/21 [==============================] - 1s 34ms/step - loss: 0.1060 - accuracy: 0.9663 - val_loss: 0.4210 - val_accuracy: 0.9167
Epoch 4/800
21/21 [==============================] - 0s 15ms/step - loss: 0.1238 - accuracy: 0.9663 - val_loss: 0.4350 - val_accuracy: 0.9062
Epoch 5/800
21/21 [==============================] - 0s 15ms/step - loss: 0.1504 - accuracy: 0.9510 - val_loss: 0.4355 - val_accuracy: 0.9271
Epoch 6/800
21/21 [==============================] - 0s 16ms/step - loss: 0.1475 - accuracy: 0.9464 - val_loss: 0.4905 - val_accuracy: 0.8958
Epoch 7/800
21/21 [==============================] - 0s 15ms/step - loss: 0.1298 - accuracy: 0.9541 - val_loss: 0.2810 - val_accuracy: 0.9271
Epoch 8/800
21/21 

In [19]:
model.save('/content/gdrive/MyDrive/code_nhandien_chuso/save_md.h5', save_format="h5")